Fix broken multi-line error message

diff --git a/Dockerfile.train b/Dockerfile.train
--- a/Dockerfile.train
+++ b/Dockerfile.train
@@ -20,10 +20,10 @@ RUN cd /code/kenlm && \
     cd build && \
     cmake .. && \
     make -j $(nproc) || \
-    echo "ERROR: Failed to build KenLM."; \
-    echo "ERROR: You must the STT repo recursively before building this Dockerfile."; \
-    echo "ERROR: $ git clone --recurse-submodules https://github.com/coqui-ai/STT.git"; \
-    exit 1;
+    ( echo "ERROR: Failed to build KenLM."; \
+    echo "ERROR: You must update the kenlm submodule on host before building this Dockerfile."; \
+    echo "ERROR: $ cd STT; git submodule update --init kenlm"; \
+    exit 1; )
 
 
 FROM ubuntu:20.04 AS wget-binaries
@@ -48,6 +48,8 @@ ENV DEBIAN_FRONTEND=noninteractive
 #
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
+        git \
+        wget \
         libopus0 \
         libopusfile0 \
         libsndfile1 \
