AAR build+publish

diff --git a/.github/actions/upload-release-asset/action.yml b/.github/actions/upload-release-asset/action.yml
--- a/.github/actions/upload-release-asset/action.yml
+++ b/.github/actions/upload-release-asset/action.yml
@@ -19,10 +19,6 @@ inputs:
     description: "Tag of release to check artifacts under"
     required: false
     default: "v0.10.0-alpha.7"
-  should-create-release:
-    description: "Whether this action should automatically create a release for the given tag if one doesn't already exist"
-    required: false
-    default: false
 runs:
   using: "composite"
   steps:
@@ -51,7 +47,6 @@ runs:
         owner=$(echo "${{inputs.repo}}" | cut -f1 -d/)
         repo=$(echo "${{inputs.repo}}" | cut -f2 -d/)
         tag="${{ inputs.release-tag }}"
-        should_create="${{ inputs.should-create-release }}"
 
         GH_REPO="https://api.github.com/repos/${owner}/${repo}"
 
@@ -75,21 +70,9 @@ runs:
         response=$(curl -sH "$AUTH" $GH_TAGS)
         eval $(echo "$response" | grep -m 1 "id.:" | grep -w id | tr : = | tr -cd '[[:alnum:]]=')
         [ "$id" ] || {
-          # If release does not exist, create it
-          if [[ "$should_create" == "true" ]]; then
-            echo "Tag does not have corresponding release, creating release for tag: $tag..."
-            response=$(curl -X POST -sH "$AUTH" -H "Content-Type: application/json" "${GH_REPO}/releases" -d '{"tag_name":"'"$tag"'","name":"Coqui STT '"$tag"'","prerelease":true}')
-            eval $(echo "$response" | grep -m 1 "id.:" | grep -w id | tr : = | tr -cd '[[:alnum:]]=')
-            [ "$id" ] || {
-              echo "Error: Could not create release for tag: $tag"
-              echo "$response" | awk 'length($0)<100' >&2
-              exit 1
-            }
-          else
-            echo "Error: Could not find release for tag: $tag"
-            echo "$response" | awk 'length($0)<100' >&2
-            exit 1
-          fi
+          echo "Error: Could not find release for tag: $tag"
+          echo "$response" | awk 'length($0)<100' >&2
+          exit 1
         }
 
         # Upload assets
