Use Ubuntu 14.04 container for building Linux binaries

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -71,6 +71,10 @@ jobs:
   swig_Linux:
     name: "Lin|Build SWIG"
     runs-on: ubuntu-20.04
+    container:
+      image: ubuntu:14.04.5
+      volumes:
+        - ${{ github.workspace }}:${{ github.workspace }}
     env:
       swig_hash: "90cdbee6a69d13b39d734083b9f91069533b0d7b"
     steps:
@@ -84,8 +88,10 @@ jobs:
         id: swig-build-cache
         with:
           path: build-static/
-          key: swig-2-${{ runner.os }}-${{ env.swig_hash }}
-      - run: |
+          key: swig-3-${{ runner.os }}-${{ env.swig_hash }}
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
           sudo apt-get install -y --no-install-recommends autoconf automake bison build-essential
         if: steps.swig-build-cache.outputs.cache-hit != 'true'
       - run: |
@@ -114,6 +120,10 @@ jobs:
     name: "Lin|Build CTC decoder Python package"
     needs: [ swig_Linux ]
     runs-on: ubuntu-20.04
+    container:
+      image: ubuntu:14.04.5
+      volumes:
+        - ${{ github.workspace }}:${{ github.workspace }}
     strategy:
       matrix:
         python-version: [3.6, 3.7, 3.8, 3.9]
@@ -121,9 +131,10 @@ jobs:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
-      - uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version }}
+      - run: |
+          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
+          pyenv install ${{ matrix.python-version }}
+          pyenv global ${{ matrix.python-version }}
       - run: |
           python --version
           pip --version
@@ -151,8 +162,6 @@ jobs:
         with:
           name: "coqui_stt_ctcdecoder-Linux-${{ matrix.python-version }}.whl"
           path: ${{ github.workspace }}/native_client/ctcdecode/dist/*.whl
-      - run: |
-          make -C native_client/ctcdecode clean-keep-third-party
   train-test-model-Linux:
     name: "Lin|Train a test model"
     needs: [ "build-ctc-decoder-Linux" ]
@@ -235,7 +244,7 @@ jobs:
       - id: get_cache_key
         uses: ./.github/actions/get_cache_key
         with:
-          extras: "2"
+          extras: "3"
       - id: check_artifact_exists
         uses: ./.github/actions/check_artifact_exists
         with:
@@ -244,34 +253,110 @@ jobs:
     name: "Lin|Build TensorFlow (opt)"
     needs: tensorflow_opt-Linux
     runs-on: ubuntu-20.04
+    env:
+      CI_TASK_DIR: /tmp/task/STT
+      CI_ARTIFACTS_DIR: /tmp/task/artifacts
+    container:
+      image: ubuntu:14.04.5
+      volumes:
+        - ${{ github.workspace }}:/tmp/task
+        - ${{ github.workspace }}/artifacts:/tmp/task/artifacts
     steps:
       - run: true
         if: needs.tensorflow_opt-Linux.outputs.status == 'found'
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-          submodules: 'recursive'
+      - name: Container and job setup
+        run: |
+          set -ex
+          mkdir -p /tmp/task
+          apt-get update
+          apt-get install -y --no-install-recommends git
+          git config --global http.sslVerify false
+          cd /tmp/task
+          rm -rf $(echo ${GITHUB_REPOSITORY} | cut -d/ -f2)
+          git clone --recursive https://github.com/${GITHUB_REPOSITORY}
+          cd $(echo ${GITHUB_REPOSITORY} | cut -d/ -f2)
+          if [[ $GITHUB_EVENT_NAME == pull_request ]]; then
+            git fetch origin $GITHUB_REF:pr_merge
+            git checkout pr_merge
+          else
+            git checkout $GITHUB_SHA
+          fi
         if: needs.tensorflow_opt-Linux.outputs.status == 'missing'
       - run: |
-          sudo apt-get install -y --no-install-recommends pixz
+          apt-get install -y --no-install-recommends \
+            build-essential \
+            gfortran \
+            libblas-dev \
+            liblapack-dev \
+            pixz \
+            python3 \
+            python3-dev \
+            python3-pip \
+            realpath \
+            software-properties-common \
+            unzip \
+            wget \
+            zip \
+            zlib1g-dev
         if: needs.tensorflow_opt-Linux.outputs.status == 'missing'
-      - uses: ./.github/actions/setup-tensorflow
+      - run: |
+          cd ${CI_TASK_DIR}
+          ./ci_scripts/tf-setup.sh
         if: needs.tensorflow_opt-Linux.outputs.status == 'missing'
-      - uses: ./.github/actions/build-tensorflow
-        with:
-          flavor: "--linux-cpu"
+      - run: |
+          cd ${CI_TASK_DIR}
+          ./ci_scripts/tf-build.sh --linux-cpu
         if: needs.tensorflow_opt-Linux.outputs.status == 'missing'
-      - uses: ./.github/actions/package-tensorflow
+      - run: |
+          cd ${CI_TASK_DIR}
+          ./ci_scripts/tf-package.sh
         if: needs.tensorflow_opt-Linux.outputs.status == 'missing'
-      - uses: ./.github/actions/upload-cache-asset
-        with:
-          name: ${{ needs.tensorflow_opt-Linux.outputs.cache_key }}.tar.xz
-          path: ${{ github.workspace }}/artifacts/home.tar.xz
+      - run: |
+          set -xe
+
+          asset_name="${{ needs.tensorflow_opt-Linux.outputs.cache_key }}.tar.xz"
+          filename="$CI_ARTIFACTS_DIR/home.tar.xz"
+
+          # Check input
+          if [[ ! -f "${filename}" ]]; then
+            echo "Error: Input file (${filename}) missing"
+            exit 1;
+          fi
+
+          AUTH="Authorization: token ${{ github.token }}"
+
+          owner=$(echo "${{ github.repository }}" | cut -f1 -d/)
+          repo=$(echo "${{ github.repository }}" | cut -f2 -d/)
+          tag="v0.10.0-alpha.7"
+
+          GH_REPO="https://api.github.com/repos/${owner}/${repo}"
+
+          # Check token
+          curl -o /dev/null -sH "$AUTH" $GH_REPO || { echo "Error: Invalid repo, token or network issue!";  exit 1; }
+
+          # Get ID of the release based on given tag name
+          GH_TAGS="${GH_REPO}/releases/tags/${tag}"
+          response=$(curl -sH "$AUTH" $GH_TAGS)
+          eval $(echo "$response" | grep -m 1 "id.:" | grep -w id | tr : = | tr -cd '[[:alnum:]]=')
+          [ "$id" ] || { echo "Error: Failed to get release id for tag: $tag"; echo "$response" | awk 'length($0)<100' >&2; exit 1; }
+
+          # Upload asset
+          echo "Uploading asset..."
+          GH_ASSET="https://uploads.github.com/repos/${owner}/${repo}/releases/${id}/assets?name=${asset_name}"
+          curl -T "${filename}" -X POST -H "${AUTH}" -H "Content-Type: application/octet-stream" $GH_ASSET
         if: needs.tensorflow_opt-Linux.outputs.status == 'missing'
   build-lib_Linux:
     name: "Lin|Build libstt+client"
     runs-on: ubuntu-20.04
     needs: [ build-tensorflow-Linux, tensorflow_opt-Linux ]
+    container:
+      image: ubuntu:14.04.5
+      env:
+        CI_TASK_DIR: ${{ github.workspace }}
+        CI_ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
+      volumes:
+        - ${{ github.workspace }}:${{ github.workspace }}
+        - ${{ github.workspace }}/artifacts:${{ github.workspace }}/artifacts
     strategy:
       matrix:
         build-flavor: ["tf", "tflite"]
@@ -307,6 +392,14 @@ jobs:
     name: "Lin|Build Python bindings"
     runs-on: ubuntu-20.04
     needs: [ build-lib_Linux, swig_Linux ]
+    container:
+      image: ubuntu:14.04.5
+      env:
+        CI_TASK_DIR: ${{ github.workspace }}
+        CI_ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
+      volumes:
+        - ${{ github.workspace }}:${{ github.workspace }}
+        - ${{ github.workspace }}/artifacts:${{ github.workspace }}/artifacts
     strategy:
       matrix:
         build-flavor: ["tf", "tflite"]
@@ -333,9 +426,13 @@ jobs:
           ls -hal ${{ github.workspace }}/native_client/ds-swig/bin
           ln -s ds-swig ${{ github.workspace }}/native_client/ds-swig/bin/swig
           chmod +x ${{ github.workspace }}/native_client/ds-swig/bin/ds-swig ${{ github.workspace }}/native_client/ds-swig/bin/swig
-      - uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version }}
+      # - uses: actions/setup-python@v2
+      #   with:
+      #     python-version: ${{ matrix.python-version }}
+      - run: |
+          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
+          pyenv install ${{ matrix.python-version }}
+          pyenv global ${{ matrix.python-version }}
       - id: get_numpy
         uses: ./.github/actions/numpy_vers
         with:
